const { generatePixPayload, normalizePixKey, validatePixKey } = window.Pix;

const STORAGE = "rateio-pix-state-v1";
const defaultState = { settings: { receiverName: "", receiverCity: "", keyType: "email", pixKey: "", defaultDescription: "", defaultTxid: "RATEIO" }, participants: [], services: [] };
function loadState() {
  try { return JSON.parse(localStorage.getItem(STORAGE) || "null") || defaultState; }
  catch { return structuredClone(defaultState); }
}
let state = loadState();
let editingServiceId = null;
const $ = (selector) => document.querySelector(selector);
function toggleServiceModes(frequency) { document.querySelectorAll(".annual-mode").forEach((element) => element.classList.toggle("hidden", frequency !== "annual")); document.querySelectorAll(".one-time-mode").forEach((element) => element.classList.toggle("hidden", frequency !== "one-time")); }
const money = (value) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
function currentReference() { const date = new Date(); const month = new Intl.DateTimeFormat("pt-BR", { month: "long" }).format(date); return `${month.charAt(0).toUpperCase()}${month.slice(1)}/${date.getFullYear()}`; }
function save() { try { localStorage.setItem(STORAGE, JSON.stringify(state)); } catch { /* A aplicação continua funcional quando aberta via file://. */ } }
function id() { return crypto.randomUUID(); }
function renderSettings() { const s = state.settings; $("#settings-summary").textContent = s.receiverName ? `${s.receiverName} · ${s.receiverCity} · ${s.pixKey}` : "Preencha seus dados para começar a gerar cobranças."; const form = $("#settings-form"); for (const [key, value] of Object.entries(s)) form.elements[key].value = value; form.classList.toggle("hidden", Boolean(s.receiverName)); $("#settings-toggle").textContent = s.receiverName ? "Editar" : ""; }
function renderParticipants() { const list = $("#participant-list"); list.innerHTML = ""; state.participants.forEach((person) => { const item = $("#participant-template").content.cloneNode(true); item.querySelector(".chip-name").textContent = person.name; item.querySelector("button").onclick = () => { state.participants = state.participants.filter((p) => p.id !== person.id); state.services.forEach((s) => s.participants = s.participants.filter((p) => p !== person.id)); save(); render(); }; list.append(item); }); const options = $("#charge-participant"); options.innerHTML = state.participants.length ? '<option value="">Escolha uma pessoa</option>' : '<option value="">Adicione participantes</option>'; state.participants.forEach((p) => options.add(new Option(p.name, p.id))); }
function renderServiceParticipantChoices(selected = null) { const box = $("#service-participants"); if (!state.participants.length) { box.innerHTML = "<legend>Quem participa?</legend><p class=\"hint\">Adicione participantes primeiro.</p>"; return; } box.innerHTML = '<legend>Quem participa?</legend><div class="checklist"></div>'; const list = box.querySelector("div"); state.participants.forEach((person) => { const label = document.createElement("label"); const checked = !selected || selected.includes(person.id) ? "checked" : ""; label.innerHTML = `<input type="checkbox" name="participants" value="${person.id}" ${checked}> ${person.name}`; list.append(label); }); }
function renderServices() { const list = $("#service-list"); list.innerHTML = ""; state.services.forEach((service) => { const item = $("#service-template").content.cloneNode(true); const divisor = service.participants.length || 1; const installments = service.installments || 1; const currentInstallment = Math.min(service.currentInstallment || 1, installments); const billed = service.frequency === "annual" && service.annualMode === "monthly" ? service.amount / 12 : service.frequency === "one-time" ? service.amount / installments : service.amount; const frequency = service.frequency === "annual" ? "ano" : service.frequency === "one-time" ? "avulso" : "mês"; item.querySelector(".service-name").textContent = service.name; item.querySelector(".service-meta").textContent = service.frequency === "one-time" ? `${money(service.amount)} · cobrança avulsa${installments > 1 ? ` · parcela ${currentInstallment} de ${installments}` : ""}` : `${money(service.amount)} / ${frequency}${service.frequency === "annual" && service.annualMode === "monthly" ? " · rateio mensal" : ""}`; item.querySelector(".service-people").textContent = `${service.participants.length} participante(s) · ${money(billed / divisor)} por pessoa`; item.querySelector(".service-amount").textContent = money(billed); item.querySelector(".edit").onclick = () => { editingServiceId = service.id; const form = $("#service-form"); form.elements.name.value = service.name; form.elements.description.value = service.description; form.elements.frequency.value = service.frequency; form.elements.amount.value = service.amount; form.elements.annualMode.value = service.annualMode || "annual"; form.elements.installments.value = service.installments || ""; form.elements.currentInstallment.value = currentInstallment; $(".annual-mode").classList.toggle("hidden", service.frequency !== "annual"); $(".one-time-mode").classList.toggle("hidden", service.frequency !== "one-time"); renderServiceParticipantChoices(service.participants); form.querySelector("button[type=submit]").textContent = "Salvar alterações"; form.scrollIntoView({ behavior: "smooth", block: "center" }); }; item.querySelector(".remove:last-child").onclick = () => { state.services = state.services.filter((s) => s.id !== service.id); if (editingServiceId === service.id) editingServiceId = null; save(); render(); }; list.append(item); }); }
function render() { renderSettings(); renderParticipants(); renderServiceParticipantChoices(); renderServices(); toggleServiceModes($("#service-form").elements.frequency.value); }
async function generateQr(payload) { if (!window.QRCode) throw new Error("Gerador de QR Code indisponível"); const container = document.createElement("div"); new window.QRCode(container, { text: payload, width: 300, height: 300, correctLevel: window.QRCode.CorrectLevel.M }); const image = container.querySelector("img"); const canvas = container.querySelector("canvas"); if (image?.src) return image.src; if (canvas) return canvas.toDataURL(); throw new Error("QR Code não foi gerado"); }
function printCharge() {
  const popup = window.open("", "_blank");
  if (!popup) { window.print(); return; }
  popup.document.write('<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Cobrança Pix</title><style>@page{size:A4;margin:14mm}body{margin:0;color:#172523;font:15px/1.45 system-ui,sans-serif}.charge-result{max-width:720px;margin:0 auto}.charge-header{padding:0 0 18px;border-bottom:2px solid #172523}.charge-header h3{margin:0 0 6px;font-size:26px;letter-spacing:-.04em}.charge-header p{margin:0;color:#62706c;font-size:14px}.charge-items{margin:18px 0}.charge-item{display:flex;justify-content:space-between;gap:20px;padding:9px 0;border-bottom:1px solid #edf0ee}.charge-item span{display:grid;gap:3px}.charge-item small{color:#62706c;font-size:12px}.charge-item strong{white-space:nowrap}.total{display:flex;justify-content:space-between;gap:20px;margin-top:14px;padding:15px 16px;background:#e8f5eb;border-radius:10px;font-size:20px}.payment{display:grid;grid-template-columns:200px 1fr;gap:28px;align-items:center;margin-top:28px;padding:24px 0 0;border-top:1px solid #dbe3de}.qr{display:block;width:190px;height:190px;margin:0 auto}.payment h4{margin:0 0 6px;font-size:18px}.payment p{margin:0 0 14px;color:#62706c}.payment .label{margin-bottom:6px;color:#172523;font-size:12px;font-weight:700;letter-spacing:.06em;text-transform:uppercase}.payload-code{padding:11px;border:1px solid #dbe3de;border-radius:8px;background:#f6f8f6;word-break:break-all;color:#31403b;font:10px/1.45 ui-monospace,monospace}.result-actions{display:none}@media(max-width:480px){.payment{grid-template-columns:1fr}.qr{margin:0}.total{font-size:18px}}</style></head><body></body></html>');
  popup.document.close();
  const result = popup.document.importNode($("#charge-result"), true);
  result.querySelector(".result-actions")?.remove();
  const qr = result.querySelector(".qr");
  const payload = result.querySelector(".payload");
  const payment = popup.document.createElement("section");
  payment.className = "payment";
  const details = popup.document.createElement("div");
  details.innerHTML = "<h4>Pagamento via Pix</h4><p>Escaneie o QR Code ou use o código copia e cola.</p><p class=\"label\">Pix copia e cola</p>";
  const payloadCode = popup.document.createElement("div");
  payloadCode.className = "payload-code";
  payloadCode.textContent = payload.value;
  payload.remove();
  details.append(payloadCode);
  payment.append(qr, details);
  result.append(payment);
  popup.document.body.append(result);
  setTimeout(() => { popup.focus(); popup.print(); popup.close(); }, 350);
}
function chargeFor(participantId) { return state.services.filter((s) => s.participants.includes(participantId)).map((s) => { const monthlyAnnual = s.frequency === "annual" && s.annualMode === "monthly"; const installments = s.installments || 1; const currentInstallment = Math.min(s.currentInstallment || 1, installments); const billed = monthlyAnnual ? s.amount / 12 : s.frequency === "one-time" ? s.amount / installments : s.amount; const calculationDetail = s.frequency === "annual" ? monthlyAnnual ? "Assinatura anual rateada mensalmente" : "Cobrança anual" : s.frequency === "one-time" ? installments > 1 ? `Despesa avulsa - parcela ${currentInstallment} de ${installments}` : "Despesa avulsa" : "Assinatura mensal"; const detail = [s.description?.trim(), calculationDetail].filter(Boolean).join(" · "); return { name: s.name, detail, amount: billed / s.participants.length }; }); }
$("#settings-toggle").onclick = () => $("#settings-form").classList.toggle("hidden");
$("#settings-form").onsubmit = (event) => { event.preventDefault(); state.settings = Object.fromEntries(new FormData(event.target)); state.settings.pixKey = normalizePixKey(state.settings.pixKey, state.settings.keyType); save(); renderSettings(); event.target.classList.add("hidden"); };
$("#participant-form").onsubmit = (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); state.participants.push({ id: id(), ...data, active: true }); save(); event.target.reset(); render(); };
$("#service-form").elements.frequency.onchange = (event) => toggleServiceModes(event.target.value);
document.addEventListener("click", (event) => { if (event.target.classList.contains("edit")) toggleServiceModes($("#service-form").elements.frequency.value); });
$("#service-form").elements.installments.oninput = (event) => { const total = Math.max(1, Number(event.target.value) || 1); const current = $("#service-form").elements.currentInstallment; current.max = total; if (Number(current.value) > total) current.value = total; };
$("#service-form").onsubmit = (event) => { event.preventDefault(); const data = new FormData(event.target); const participants = data.getAll("participants"); if (!participants.length) return; const installments = Math.max(1, Number(data.get("installments")) || 1); const service = { id: editingServiceId || id(), name: data.get("name"), description: data.get("description"), frequency: data.get("frequency"), amount: Number(data.get("amount")), annualMode: data.get("annualMode"), installments, currentInstallment: Math.min(installments, Math.max(1, Number(data.get("currentInstallment")) || 1)), participants }; state.services = editingServiceId ? state.services.map((item) => item.id === editingServiceId ? service : item) : [...state.services, service]; editingServiceId = null; save(); event.target.reset(); event.target.querySelector("button[type=submit]").textContent = "Adicionar serviço"; render(); };
$("#charge-form").onsubmit = async (event) => { event.preventDefault(); const form = new FormData(event.target); const person = state.participants.find((p) => p.id === form.get("participant")); const items = chargeFor(person?.id); const total = items.reduce((sum, item) => sum + item.amount, 0); const key = normalizePixKey(state.settings.pixKey, state.settings.keyType); const error = validatePixKey(key, state.settings.keyType); const result = $("#charge-result"); if (!person || !items.length || error || !state.settings.receiverName || !state.settings.receiverCity) { result.className = "charge-result error"; result.textContent = error || "Configure os dados e associe ao menos um serviço a esta pessoa."; return; } const description = form.get("description") || state.settings.defaultDescription || `Assinaturas ${form.get("reference")}`; const payload = generatePixPayload({ key, description, amount: total, receiverName: state.settings.receiverName, receiverCity: state.settings.receiverCity, txid: state.settings.defaultTxid || "***" }); const dueDate = form.get("dueDate"); const dueText = dueDate ? ` · Vence em ${new Date(`${dueDate}T12:00:00`).toLocaleDateString("pt-BR")}` : ""; result.className = "charge-result"; result.innerHTML = `<div class="charge-header"><h3>Rateio de assinaturas</h3><p>${person.name} · ${form.get("reference")}${dueText}</p></div><div class="charge-items">${items.map((item) => `<div class="charge-item"><span>${item.name}<small>${item.detail}</small></span><strong>${money(item.amount)}</strong></div>`).join("")}</div><div class="total"><strong>Total</strong><strong>${money(total)}</strong></div><img class="qr" alt="QR Code Pix"><textarea class="payload" readonly>${payload}</textarea><div class="result-actions"><button class="button primary" type="button" id="copy-pix">Copiar Pix</button><button class="button" type="button" id="print-charge">Imprimir</button></div>`; try { result.querySelector(".qr").src = await generateQr(payload); } catch { result.querySelector(".qr").remove(); } $("#copy-pix").onclick = async () => { await navigator.clipboard.writeText(payload); $("#copy-pix").textContent = "Copiado!"; }; $("#print-charge").onclick = () => window.print(); };
$("#charge-form").elements.reference.value = currentReference();
render();
document.addEventListener("click", (event) => { if (event.target.id !== "print-charge") return; event.preventDefault(); event.stopImmediatePropagation(); printCharge(); }, true);
if ("serviceWorker" in navigator && location.protocol !== "file:") window.addEventListener("load", () => navigator.serviceWorker.register("./sw.js").catch(() => {}));
