const { generatePixPayload, normalizePixKey, validatePixKey } = window.Pix;

const STORAGE = "rateio-pix-state-v1";
const defaultState = { settings: { receiverName: "", receiverCity: "", keyType: "email", pixKey: "", defaultDescription: "", defaultTxid: "RATEIO" }, participants: [], services: [] };
function loadState() {
  try { return JSON.parse(localStorage.getItem(STORAGE) || "null") || defaultState; }
  catch { return structuredClone(defaultState); }
}
let state = loadState();
let editingServiceId = null;
const $ = (selector) => document.querySelector(selector);
function toggleServiceModes(frequency) { document.querySelectorAll(".annual-mode").forEach((element) => element.classList.toggle("hidden", frequency !== "annual")); document.querySelectorAll(".one-time-mode").forEach((element) => element.classList.toggle("hidden", frequency !== "one-time")); }
const money = (value) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
function currentReference() { const date = new Date(); const month = new Intl.DateTimeFormat("pt-BR", { month: "long" }).format(date); return `${month.charAt(0).toUpperCase()}${month.slice(1)}/${date.getFullYear()}`; }
function save() { try { localStorage.setItem(STORAGE, JSON.stringify(state)); } catch { /* A aplicação continua funcional quando aberta via file://. */ } }
function id() { return crypto.randomUUID(); }
function renderSettings() { const s = state.settings; $("#settings-summary").textContent = s.receiverName ? `${s.receiverName} · ${s.receiverCity} · ${s.pixKey}` : "Preencha seus dados para começar a gerar cobranças."; const form = $("#settings-form"); for (const [key, value] of Object.entries(s)) form.elements[key].value = value; form.classList.toggle("hidden", Boolean(s.receiverName)); $("#settings-toggle").textContent = s.receiverName ? "Editar" : ""; }
function renderParticipants() { const list = $("#participant-list"); list.innerHTML = ""; state.participants.forEach((person) => { const item = $("#participant-template").content.cloneNode(true); item.querySelector(".chip-name").textContent = person.name; item.querySelector("button").onclick = () => { state.participants = state.participants.filter((p) => p.id !== person.id); state.services.forEach((s) => s.participants = s.participants.filter((p) => p !== person.id)); save(); render(); }; list.append(item); }); const options = $("#charge-participant"); options.innerHTML = state.participants.length ? '<option value="">Escolha uma pessoa</option>' : '<option value="">Adicione participantes</option>'; state.participants.forEach((p) => options.add(new Option(p.name, p.id))); }
function renderServiceParticipantChoices(selected = null) { const box = $("#service-participants"); if (!state.participants.length) { box.innerHTML = "<legend>Quem participa?</legend><p class=\"hint\">Adicione participantes primeiro.</p>"; return; } box.innerHTML = '<legend>Quem participa?</legend><div class="checklist"></div>'; const list = box.querySelector("div"); state.participants.forEach((person) => { const label = document.createElement("label"); const checked = !selected || selected.includes(person.id) ? "checked" : ""; label.innerHTML = `<input type="checkbox" name="participants" value="${person.id}" ${checked}> ${person.name}`; list.append(label); }); }
function renderServices() { const list = $("#service-list"); list.innerHTML = ""; state.services.forEach((service) => { const item = $("#service-template").content.cloneNode(true); const divisor = service.participants.length || 1; const installments = service.installments || 1; const currentInstallment = Math.min(service.currentInstallment || 1, installments); const billed = service.frequency === "annual" && service.annualMode === "monthly" ? service.amount / 12 : service.frequency === "one-time" ? service.amount / installments : service.amount; const frequency = service.frequency === "annual" ? "ano" : service.frequency === "one-time" ? "avulso" : "mês"; item.querySelector(".service-name").textContent = service.name; item.querySelector(".service-meta").textContent = service.frequency === "one-time" ? `${money(service.amount)} · cobrança avulsa${installments > 1 ? ` · parcela ${currentInstallment} de ${installments}` : ""}` : `${money(service.amount)} / ${frequency}${service.frequency === "annual" && service.annualMode === "monthly" ? " · rateio mensal" : ""}`; item.querySelector(".service-people").textContent = `${service.participants.length} participante(s) · ${money(billed / divisor)} por pessoa`; item.querySelector(".service-amount").textContent = money(billed); item.querySelector(".edit").onclick = () => { editingServiceId = service.id; const form = $("#service-form"); form.elements.name.value = service.name; form.elements.description.value = service.description; form.elements.frequency.value = service.frequency; form.elements.amount.value = service.amount; form.elements.annualMode.value = service.annualMode || "annual"; form.elements.installments.value = service.installments || ""; form.elements.currentInstallment.value = currentInstallment; $(".annual-mode").classList.toggle("hidden", service.frequency !== "annual"); $(".one-time-mode").classList.toggle("hidden", service.frequency !== "one-time"); renderServiceParticipantChoices(service.participants); form.querySelector("button[type=submit]").textContent = "Salvar alterações"; form.scrollIntoView({ behavior: "smooth", block: "center" }); }; item.querySelector(".remove:last-child").onclick = () => { state.services = state.services.filter((s) => s.id !== service.id); if (editingServiceId === service.id) editingServiceId = null; save(); render(); }; list.append(item); }); }
function render() { renderSettings(); renderParticipants(); renderServiceParticipantChoices(); renderServices(); toggleServiceModes($("#service-form").elements.frequency.value); }
function renderQr(container, payload) {
  if (!window.QRCode) throw new Error("Gerador de QR Code indisponível");
  new window.QRCode(container, { text: payload, width: 300, height: 300, correctLevel: window.QRCode.CorrectLevel.M });
  if (!container.querySelector("canvas, img, svg, table")) throw new Error("QR Code não foi gerado");
}
function chargeFor(participantId) { return state.services.filter((s) => s.participants.includes(participantId)).map((s) => { const monthlyAnnual = s.frequency === "annual" && s.annualMode === "monthly"; const installments = s.installments || 1; const currentInstallment = Math.min(s.currentInstallment || 1, installments); const billed = monthlyAnnual ? s.amount / 12 : s.frequency === "one-time" ? s.amount / installments : s.amount; const calculationDetail = s.frequency === "annual" ? monthlyAnnual ? "Assinatura anual rateada mensalmente" : "Cobrança anual" : s.frequency === "one-time" ? installments > 1 ? `Despesa avulsa - parcela ${currentInstallment} de ${installments}` : "Despesa avulsa" : "Assinatura mensal"; const detail = [s.description?.trim(), calculationDetail].filter(Boolean).join(" · "); return { name: s.name, detail, amount: billed / s.participants.length }; }); }
$("#settings-toggle").onclick = () => $("#settings-form").classList.toggle("hidden");
$("#settings-form").onsubmit = (event) => { event.preventDefault(); state.settings = Object.fromEntries(new FormData(event.target)); state.settings.pixKey = normalizePixKey(state.settings.pixKey, state.settings.keyType); save(); renderSettings(); event.target.classList.add("hidden"); };
$("#participant-form").onsubmit = (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); state.participants.push({ id: id(), ...data, active: true }); save(); event.target.reset(); render(); };
$("#service-form").elements.frequency.onchange = (event) => toggleServiceModes(event.target.value);
document.addEventListener("click", (event) => { if (event.target.classList.contains("edit")) toggleServiceModes($("#service-form").elements.frequency.value); });
$("#service-form").elements.installments.oninput = (event) => { const total = Math.max(1, Number(event.target.value) || 1); const current = $("#service-form").elements.currentInstallment; current.max = total; if (Number(current.value) > total) current.value = total; };
$("#service-form").onsubmit = (event) => { event.preventDefault(); const data = new FormData(event.target); const participants = data.getAll("participants"); if (!participants.length) return; const installments = Math.max(1, Number(data.get("installments")) || 1); const service = { id: editingServiceId || id(), name: data.get("name"), description: data.get("description"), frequency: data.get("frequency"), amount: Number(data.get("amount")), annualMode: data.get("annualMode"), installments, currentInstallment: Math.min(installments, Math.max(1, Number(data.get("currentInstallment")) || 1)), participants }; state.services = editingServiceId ? state.services.map((item) => item.id === editingServiceId ? service : item) : [...state.services, service]; editingServiceId = null; save(); event.target.reset(); event.target.querySelector("button[type=submit]").textContent = "Adicionar serviço"; render(); };
$("#charge-form").onsubmit = async (event) => { event.preventDefault(); const form = new FormData(event.target); const person = state.participants.find((p) => p.id === form.get("participant")); const items = chargeFor(person?.id); const total = items.reduce((sum, item) => sum + item.amount, 0); const key = normalizePixKey(state.settings.pixKey, state.settings.keyType); const error = validatePixKey(key, state.settings.keyType); const result = $("#charge-result"); if (!person || !items.length || error || !state.settings.receiverName || !state.settings.receiverCity) { result.className = "charge-result error"; result.textContent = error || "Configure os dados e associe ao menos um serviço a esta pessoa."; return; } const description = form.get("description") || state.settings.defaultDescription || `Assinaturas ${form.get("reference")}`; const payload = generatePixPayload({ key, description, amount: total, receiverName: state.settings.receiverName, receiverCity: state.settings.receiverCity, txid: state.settings.defaultTxid || "***" }); const dueDate = form.get("dueDate"); const dueText = dueDate ? ` · Vence em ${new Date(`${dueDate}T12:00:00`).toLocaleDateString("pt-BR")}` : ""; result.className = "charge-result"; result.innerHTML = `<div class="charge-header"><h3>Rateio de assinaturas</h3><p>${person.name} · ${form.get("reference")}${dueText}</p></div><div class="charge-items">${items.map((item) => `<div class="charge-item"><span>${item.name}<small>${item.detail}</small></span><strong>${money(item.amount)}</strong></div>`).join("")}</div><div class="total"><strong>Total</strong><strong>${money(total)}</strong></div><div class="qr" role="img" aria-label="QR Code Pix"></div><textarea class="payload" readonly>${payload}</textarea><div class="result-actions"><button class="button primary" type="button" id="copy-pix">Copiar Pix</button><button class="button" type="button" id="print-charge">Imprimir</button></div>`; try { renderQr(result.querySelector(".qr"), payload); } catch (qrError) { const qr = result.querySelector(".qr"); qr.className = "qr-error"; qr.textContent = qrError.message; } $("#copy-pix").onclick = async () => { await navigator.clipboard.writeText(payload); $("#copy-pix").textContent = "Copiado!"; }; $("#print-charge").onclick = () => window.print(); };
$("#charge-form").elements.reference.value = currentReference();
render();
if ("serviceWorker" in navigator && location.protocol !== "file:") window.addEventListener("load", () => navigator.serviceWorker.register("./sw.js", { updateViaCache: "none" }).catch(() => {}));
